### ISSUE TITLE
load yetibot.core locally

### ISSUE THREAD

**Issue by include** [yetibot/community#1]
Hi,

This is more a Clojure question than anything but :)...
How can I see (load) my yetibot.core changes locally?
Do I need to change something under yetibot project.clj?

Thanks

Cheers,
Francisco

**Comment by devth** [comment]
I typically work on yetibot.core independent from the main Yetibot. `yetibot.core` has all the core functionality necessary to connect to Slack and run basic commands. 

If you do need to test out changes, you can `lein install` in `yetibot.core`, then in `yetibot`, bump the `yetibot.core` dependency to the latest snapshot that you just installed, and run it or start the repl.

The down side is any time you need to make a change and test you have to do the above steps all over again and restart your repl or yetibot.

lein has [Checkout Dependencies](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) to help with this situation, but I almost never use them since I just work on `yetibot.core` independently.

**Comment by include** [comment]
So you work always in `yetibot.core` but some changes are meant to `yetibot`.
When you are ok with something you were building, do you move your code to `yetibot` and push your changes to the repo?

**Comment by devth** [comment]
Sorry @include, I forgot about this 😕

I build features in whichever module I think it belongs. More essential features I put in yetibot.core, while heavier and more obscure features I put in yetibot. But I'm not 100% consistent.

**Comment by devth** [comment]
Closing for now but let me know if you have follow up questions!
